spring.application.name=FileConnect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.s3.accessKey=${AWS_ACCESS_KEY}
aws.s3.secretKey=${AWS_SECRET_KEY}
aws.s3.bucketName=${AWS_BUCKET_NAME}
aws.s3.region=${AWS_REGION}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true