spring.application.name=FileConnect

spring.datasource.url=jdbc:postgresql://fileconnect.cdycseo465fe.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=fileconnect

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


aws.s3.accessKey=AKIA4UVXYXWAPN6TLOCR
aws.s3.secretKey=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
aws.s3.bucketName=fileconnect-bucket
aws.s3.region=ap-south-1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashmulik95@gmail.com
spring.mail.password=wcyh fmyj uyjd oius

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

